import { Address } from '../models/addressModel';


export const AllProvince: Address[] = [
  { name: 'Abra'},
  { name: 'Agusan Del Norte'},
  { name: 'Agusan Del Sur'},
  { name: 'Aklan'},
  { name: 'Albay'},
  { name: 'Antique'},
  { name: 'Apayao'},
  { name: 'Aurora'},
  { name: 'Basilan'},
  { name: 'Bataan'},
  { name: 'Batanes'},
  { name: 'Batangas'},
  { name: 'Benguet'},
  { name: 'Biliran'},
  { name: 'Bohol'},
  { name: 'Bukidnon'},
  { name: 'Bulacan'},   
  { name: 'Cagayan'},
  { name: 'Camarines Norte'},
  { name: 'Camarines Sur'},
  { name: 'Camiguin'},
  { name: 'Capiz'},
  { name: 'Catanduanes'},
  { name: 'Cavite'},
  { name: 'Cebu'},
  { name: 'Compostella Valley'},
  { name: 'Cotabato'},
  { name: 'Davao Del Norte'},
  { name: 'Davao Del Sur'},
  { name: 'Davao Occidental'},
  { name: 'Davao Oriental'},
  { name: 'Dinagat Islands'},
  { name: 'Eastern Samar'},
  { name: 'Guimaras'},
  { name: 'Ifugao'},
  { name: 'Ilocos Norte'},
  { name: 'Ilocos Sur'},
  { name: 'Iloilo'},
  { name: 'Isabela'},
  { name: 'Kalinga'},
  { name: 'La Union'},
  { name: 'Laguna'},
  { name: 'Lanao Del Norte'},
  { name: 'Lanao Del Sur'},
  { name: 'Leyte M'},
  { name: 'Maguindanao'},
  { name: 'Marinduque'},
  { name: 'Masbate'},
  { name: 'Misamis Occidental'},
  { name: 'Misamis Oriental'},
  { name: 'Mountain Province'},
  { name: 'Negros Occidental'},
  { name: 'Negros Oriental'},
  { name: 'Northern Samar'},
  { name: 'Nueva Ecija'},
  { name: 'Nueva Vizcaya'},
  { name: 'Occidental Mindoro'},
  { name: 'Oriental Mindoro'},
  { name: 'Palawan'},
  { name: 'Pampanga'},
  { name: 'Pangasinan'},
  { name: 'Quezon'},
  { name: 'Quirino'},
  { name: 'Rizal'},
  { name: 'Romblon'},
  { name: 'Samar'},
  { name: 'Sarangani'},
  { name: 'Siquijor'},
  { name: 'Sorsogon'},
  { name: 'South Cotabato'},
  { name: 'Southern Leyte'},
  { name: 'Sultan Kudarat'},
  { name: 'Sulu'},
  { name: 'Surigao Del Norte'},
  { name: 'Surigao Del Sur'},
  { name: 'Tarlac'},
  { name: 'Tawi-Tawi'},
  { name: 'Zambales'},
  { name: 'Zamboanga Del Norte'},
  { name: 'Zamboanga Del Sur'},
  { name: 'Zamboanga Sibugay'},
];

/*
Copyright 2017-2018 Google Inc. All Rights Reserved.
Use of this source code is governed by an MIT-style license that
can be found in the LICENSE file at http://angular.io/license
*/